#User Database

class Database:
    def __init__(self):
        self.hero =     {
                         'Lúcio':'Lucio',
                         'Torbjörn':'Torbjorn'
                         #'温斯顿' : 'Winston',
                         #'破坏球' : 'Wrecking Ball',
                         #'士兵' : 'Soldier: 76',
                         #'秩序之光' : 'Symmetra',
                         #'奥丽莎' : 'Orisa',
                         #'卢西奥' : 'Lucio',
                         #'回声' : 'Echo',
                         #'安娜' : 'Ana',
                         #'源氏' : 'Genji',
                         #'末日铁拳' : 'Doomfist',
                         #'死神' : 'Reaper',
                         #'麦克雷' : 'McCree',
                         #'美' : 'Mei',
                         #'堡垒' : 'Bastion',
                         #'黑影' : 'Sombra',
                         #'艾什' : 'Ashe',
                         #'黑百合' : 'Widowmaker',
                         #'狂鼠' : 'Junkrat',
                         #'托比昂' : 'Torbjorn',
                         #'猎空' : 'Tracer',
                         #'法老之鹰' : 'Pharah',
                         #'半藏' : 'Hanzo',
                         #'莱因哈特' : 'Reinhardt',
                         #'路霸' : 'Roadhog',
                         #'查莉娅' : 'Zarya',
                         #'天使' : 'Mercy',
                         #'莫伊拉' : 'Moira',
                         #'巴蒂斯特' : 'Baptiste',
                         #'布丽吉塔' : 'Brigitte',
                         #'禅雅塔' : 'Zenyatta',
                         #'西格玛' : 'Sigma'
                        }

        self.player =   {
                         'Lúcio':'Lucio',
                         'Torbjörn':'Torbjorn',
                         '훈련용봇':'ivy',
                         '광붕이':'Gwangboong', 
                         '방준배':'JJonak', 
                         'Azhy':'BiaNcA',
                         '알파이':'AlphaYi', 
                         'RUNNER':'Simple', 
                         'thousand':'Ado',
                         'ATL008':'Edison',
                         'NYE001':'Friday',
                         'NYE004':'JJonak',
                         'NYE029':'Yakpung',
                         'NYE013':'BiaNcA',
                         'NYE012':'Flora',
                         'NYE023':'Gwangboong',
                         'NYE007':'ivy',
                         'NYE014':'Feath5r',
                         'NYE044':'JJonak',
                         'NYE005':'Kalios',
                         'NYE025':'Undine',
                         'Lafan':'Choisehwan',
                         'HZS010':'SEOMINSOO',
                         'HZS009':'GodsB',
                         'HZS007':'SHY',
                         'HZS008':'Guxue',
                         'HZS011':'Bernar',
                         'HZS001':'iDK',
                         'HZS002':'MCD',
                         'HZS003':'Takoyaki',
                         'HZS012':'Architect',
                         'HZS004':'ColdesT',
                         'HZS006':'M1ka',
                         'HZS005':'Lige',
                         'VAL012':'Krystal',
                         'VAL001':'MoLanran',
                         'VAL003':'Silver3',
                         'VAL004':'ShowCheng',
                         'VAL002':'Highbee',
                         'VAL005':'wya',
                         'Popstar':'MYKaylee',
                         'STAR':'MYKaylee',
                         '이자야키':'Izayaki',
                         '빡겜유저이재곤':'LeeJaeGon',
                         'DIZAN':'Diem',
                         'qpdbdbqp':'Erster',
                         'ropz':'Molly',
                         'IwillbeBest':'Architect',
                         'Silver':'Silver3',
                         'Korppi':'Wya',
                         'MT1Krystal':'Krystal',
                         'Unhappy':'Highbee',
                         'TrumpCard':'MoLanran',
                         'Liuzixuan':'LIP',
                         'SorryMaker':'Sleep',
                         'Freaks':'n1ghtg0d',
                         '태도':'Attitude',
                         '폴라폴라포':'PolaPo',
                         '에베베벱메롱메롱':'CH0R0NG',
                         'YaHo2':'YaHo',
                         'PHI003':'Carpe',
                         'PHI004':'eqo',
                         'PHI008':'Rascal',
                         'PHI001':'Mano',
                         'PHI010':'Hotba',
                         'PHI011':'Tobi',
                         'PHI006':'Alarm',
                         'PHI007':'FunnyAstro',
                         'GZC003':'MYKaylee',
                         'GZC007':'Choisehwan',
                         'GZC014':'Rio',
                         'GZC013':'Cr0ng',
                         'GZC021':'Mandu',
                         'GZC008':'Kariv',
                         'GZC005':'JIHUN',
                         'GZC010':'Eileen',
                         'SEO001':'Fits',
                         'SEO007':'Profit',
                         'SEO004':'Gesture',
                         'SEO006':'ToYou',
                         'SEO008':'Anamo',
                         'SEO012':'Creative',
                         'SEO005':'Marve1',
                         'CDH007':'GA9A',
                         'CDH099':'Elsa',
                         'CDH003':'Yveltal',
                         'CDH001':'Farway1987',
                         'CDH026':'Jinmu',
                         'CDH002':'Leave',
                         'CDH010':'Nisha',
                         'CDH013':'MMonk',
                         'CDH025':'Jimmy',
                         'CDH088':'TaroCookie',
                         'CDH017':'Ameng',
                         'SHD006':'LIP',
                         'SHD005':'Fleta',
                         'SHD001':'Void',
                         'SHD002':'Fate',
                         'SHD009':'LeeJaeGon',
                         'SHD008':'Izayaki',
                         'SHD004':'Diem',
                         'SHD007':'Molly',
                         'SHD018':'WhoRu',
                         'SHD022':'Develop',
                         'TALSpare1':'PERFACT',
                         'NYE021':'Whynot',
                         'NYE026':'Schwi',
                         'TBMSub3':'CHaN',
                         'TBMSub4':'Caffeine',
                         'WGSPStaff4':'ALBAM',
                         'WGSPSpare5':'Hyunwoo',
                         'TALSub1':'Ado',
                         'TALSub2':'Cane'
                        }