#User Database

class Database:
    def __init__(self):
        self.hero =     {
                         'Lúcio':'Lucio',
                         'Torbjörn':'Torbjorn'
                        }

        self.player =   {
                         'Lúcio':'Lucio',
                         'Torbjörn':'Torbjorn',
                         '훈련용봇':'ivy',
                         '광붕이':'Gwangboong', 
                         '방준배':'JJonak', 
                         'Azhy':'BiaNcA',
                         '알파이':'AlphaYi', 
                         'RUNNER':'Simple', 
                         'thousand':'Ado',
                         'ATL008':'Edison',
                         'NYE001':'Friday',
                         'NYE004':'JJonak',
                         'NYE029':'Yakpung',
                         'NYE013':'BiaNcA',
                         'NYE012':'Flora',
                         'NYE023':'Gwangboong',
                         'NYE007':'ivy',
                         'NYE014':'Feath5r',
                         'Lafan':'Choisehwan',
                         'HZS010':'SEOMINSOO',
                         'HZS009':'GodsB',
                         'HZS007':'SHY',
                         'HZS008':'Takoyaki',
                         'HZS011':'Bernar',
                         'HZS001':'iDK',
                         'HZS002':'MCD',
                         'HZS003':'Guxue',
                         'HZS012':'Architect',
                         'VAL012':'Krystal',
                         'VAL001':'MoLanran',
                         'VAL003':'Silver3',
                         'VAL004':'ShowCheng',
                         'VAL002':'Highbee',
                         'VAL005':'wya',
                         'Popstar':'MYKaylee',
                         'STAR':'MYKaylee',
                         '이자야키':'Izayaki',
                         '빡겜유저이재곤':'LeeJaeGon',
                         'DIZAN':'Diem',
                         'qpdbdbqp':'Erster',
                         'ropz':'Molly',
                         'IwillbeBest':'Architect',
                         'Silver':'Silver3',
                         'Korppi':'Wya',
                         'MT1Krystal':'Krystal',
                         'Unhappy':'Highbee',
                         'TrumpCard':'MoLanran',
                         'Liuzixuan':'LIP',
                         'SorryMaker':'Sleep',
                         'Freaks':'n1ghtg0d',
                         '태도':'Attitude',
                         '폴라폴라포':'PolaPo',
                         '에베베벱메롱메롱':'CH0R0NG',
                         'YaHo2':'YaHo'
                        }
